### ISSUE TITLE
How do I use this gem together with your ravepay react component?

### ISSUE THREAD

**Issue by andrew-oko-odion** [Flutterwave/Ruby#1]
I have a Rails api only backend and I am trying to integrate Flutterwave, but kind of confused how this all tie up, 
especially because there is no UI on this gem

Does that mean, I should spring up my own UI or add up your Ravepay React componenet to my React frontend?

**Comment by corneliusyaovi** [comment]
Hi @andrew-oko-odion,

You can choose to handle payments on the frontend using the React component or on the backend using this library. It is easier to handle all the payments on your backend as you would need to verify payments on your backend server. I'd advise you to consider your payment flow and infrastructure before deciding which works best.
